export const appointments = [
  {
    id: "1",
    userId: "1",
    salonId: "1",
    salonName: "Hair Avenue",
    image: "https://source.unsplash.com/600x400/?salon,hair", // demo зураг
    serviceId: "1",
    stylistId: "1",
    date: "2025-04-26",
    time: "10:00 AM",
    status: "Баталгаажсан",
    price: 35,
    duration: 45,
    location: "Lakewood, California",
  },
  {
    id: "2",
    userId: "1",
    salonId: "2",
    salonName: "Modern Beauty Salon",
    image: "https://source.unsplash.com/600x400/?beauty,salon",
    serviceId: "3",
    stylistId: "3",
    date: "2025-05-03",
    time: "2:30 PM",
    status: "Хүлээгдэж байна",
    price: 25,
    duration: 30,
    location: "Los Angeles, California",
  },
  {
    id: "3",
    userId: "1",
    salonId: "1",
    salonName: "Hair Avenue",
    image: "https://source.unsplash.com/600x400/?hairdresser",
    serviceId: "5",
    stylistId: "4",
    date: "2025-04-15",
    time: "4:00 PM",
    status: "Дууссан",
    price: 50,
    duration: 60,
    location: "Lakewood, California",
  },
  {
    id: "4",
    userId: "1",
    salonId: "3",
    salonName: "CL Salon",
    image: "https://source.unsplash.com/600x400/?barber,salon",
    serviceId: "5",
    stylistId: "4",
    date: "2025-04-10",
    time: "12:00 PM",
    status: "Цуцлагдсан",
    price: 40,
    duration: 40,
    location: "San Diego, California",
  },
];
