// Mock data for the salon booking application
export const appointments = [
  {
    id: "1",
    userId: "1",
    salonId: "1",
    salonName: "Hair Avenue",
    image: "https://source.unsplash.com/600x400/?salon,hair", // demo image
    serviceId: "1",
    stylistId: "1",
    date: "Sep 10, 2024",
    time: "9:30 AM",
    status: "Баталгаажсан", // Confirmed
    price: 35,
    duration: 45,
    location: "Lakewood, California",
    services: "Hair Cut, Hair Wash",
  },
  {
    id: "2",
    userId: "1",
    salonId: "1",
    salonName: "Hair Avenue",
    image: "https://source.unsplash.com/600x400/?salon,hair",
    serviceId: "3",
    stylistId: "3",
    date: "Sep 28, 2024",
    time: "9:30 AM",
    status: "Хүлээгдэж байна", // Pending
    price: 25,
    duration: 30,
    location: "Lakewood, California",
    services: "Hair Cut, Hair Wash",
  },
  {
    id: "3",
    userId: "1",
    salonId: "3",
    salonName: "CL Salon",
    image: "https://source.unsplash.com/600x400/?barber,salon",
    serviceId: "5",
    stylistId: "4",
    date: "Sep 5, 2024",
    time: "11:30 AM",
    status: "Дууссан", // Completed
    price: 40,
    duration: 40,
    location: "Lakewood, California",
    services: "Hair Cut, Hair Wash",
  },
  {
    id: "4",
    userId: "1",
    salonId: "2",
    salonName: "Mcolors Beauty Salon",
    image: "https://source.unsplash.com/600x400/?beauty,salon",
    serviceId: "3",
    stylistId: "3",
    date: "Aug 15, 2024",
    time: "9:00 AM",
    status: "Дууссан", // Completed
    price: 25,
    duration: 30,
    location: "Lakewood, California",
    services: "Hair Cut, Hair Wash",
  },
  {
    id: "5",
    userId: "1",
    salonId: "1",
    salonName: "Hair Avenue",
    image: "https://source.unsplash.com/600x400/?salon,hair",
    serviceId: "5",
    stylistId: "4",
    date: "Sep 27, 2024",
    time: "11:30 AM",
    status: "Цуцлагдсан", // Cancelled
    price: 50,
    duration: 60,
    location: "Lakewood, California",
    services: "Hair Cut, Hair Wash",
  },
  {
    id: "6",
    userId: "1",
    salonId: "2",
    salonName: "Mcolors Beauty Salon",
    image: "https://source.unsplash.com/600x400/?beauty,salon",
    serviceId: "5",
    stylistId: "4",
    date: "Aug 14, 2024",
    time: "9:00 AM",
    status: "Цуцлагдсан", // Cancelled
    price: 40,
    duration: 40,
    location: "Lakewood, California",
    services: "Hair Cut, Hair Wash",
  },
];
