export const appointments = [
  {
    id: "1",
    userId: "1",
    salonId: "1",
    serviceId: "1",
    stylistId: "1",
    date: "2025-04-26",
    time: "10:00 AM",
    status: "Баталгаажсан",
    price: 35,
    duration: 45,
  },
  {
    id: "2",
    userId: "1",
    salonId: "2",
    serviceId: "3",
    stylistId: "3",
    date: "2025-05-03",
    time: "2:30 PM",
    status: "Хүлээгдэж байна",
    price: 25,
    duration: 30,
  },
  {
    id: "3",
    userId: "1",
    salonId: "1",
    serviceId: "5",
    stylistId: "4",
    date: "2025-04-15",
    time: "4:00 PM",
    status: "Дууссан",
    price: 50,
    duration: 60,
  },
];
