export const salons = [
  {
    id: "1",
    name: "Glamour Beauty Salon",
    address: "123 Main Street, City",
    rating: 4.8,
    reviews: 245,
    imageUrl: "https://via.placeholder.com/150",
    description: "Premium beauty salon offering a wide range of services.",
    phone: "+1-123-456-7890",
    workingHours: "9:00 AM - 7:00 PM",
    featured: true,
  },
  {
    id: "2",
    name: "Hair Masters",
    address: "456 Elm Street, City",
    rating: 4.5,
    reviews: 187,
    imageUrl: "https://via.placeholder.com/150",
    description: "Specialized in hair styling and coloring.",
    phone: "+1-123-456-7891",
    workingHours: "10:00 AM - 8:00 PM",
    featured: true,
  },
  {
    id: "3",
    name: "Nails & Beyond",
    address: "789 Oak Street, City",
    rating: 4.7,
    reviews: 159,
    imageUrl: "https://via.placeholder.com/150",
    description: "Expert nail services with premium products.",
    phone: "+1-123-456-7892",
    workingHours: "9:00 AM - 6:00 PM",
    featured: false,
  },
];
