export const salons = [
  {
    id: "1",
    name: "Салон",
    address: "Улаанбаатар, Сүхбаатар дүүрэг, 1-р хороо",
    rating: 4.8,
    reviews: 245,
    imageUrl: "https://via.placeholder.com/150",
    description:
      "Бүх төрлийн гоо сайхны үйлчилгээ үзүүлдэг дээд зэрэглэлийн салон.",
    phone: "+976-99112233",
    workingHours: "09:00 - 19:00",
    featured: true,
  },
  {
    id: "2",
    name: "Үсчин",
    address: "Улаанбаатар, Баянзүрх дүүрэг, 5-р хороо",
    rating: 4.5,
    reviews: 187,
    imageUrl: "https://via.placeholder.com/150",
    description: "Үс засалт болон өнгө оруулах мэргэшсэн үйлчилгээтэй.",
    phone: "+976-88112233",
    workingHours: "10:00 - 20:00",
    featured: true,
  },
  {
    id: "3",
    name: "Хумс будалт",
    address: "Улаанбаатар, Хан-Уул дүүрэг, 3-р хороо",
    rating: 4.7,
    reviews: 159,
    imageUrl: "https://via.placeholder.com/150",
    description: "Дээд зэрэглэлийн бүтээгдэхүүнээр гоёмсог хумсны үйлчилгээ.",
    phone: "+976-77112233",
    workingHours: "09:00 - 18:00",
    featured: false,
  },
];
