export const services = [
  {
    id: "1",
    name: "Үс засалт",
    description: "Манай туршлагатай үсчдээр мэргэжлийн үс засалт хийлгээрэй",
    price: 35000, // төгрөг
    duration: 45, // минут
    imageUrl: "https://via.placeholder.com/150",
    category: "hair",
  },
  {
    id: "2",
    name: "Үсний өнгө оруулах",
    description: "Дээд зэрэглэлийн будаг ашиглан бүх үс өнгө оруулах үйлчилгээ",
    price: 85000,
    duration: 120,
    imageUrl: "https://via.placeholder.com/150",
    category: "hair",
  },
  {
    id: "3",
    name: "Маникюр",
    description: "Сонгосон будагтай сонгодог маникюр үйлчилгээ",
    price: 25000,
    duration: 30,
    imageUrl: "https://via.placeholder.com/150",
    category: "nails",
  },
  {
    id: "4",
    name: "Педикюр",
    description: "Амралтын педикюр, гуужуулалт болон массажтай",
    price: 35000,
    duration: 45,
    imageUrl: "https://via.placeholder.com/150",
    category: "nails",
  },
  {
    id: "5",
    name: "Нүүр арчилгаа",
    description: "Дээд зэрэглэлийн бүтээгдэхүүнээр нүүр цэвэрлэх үйлчилгээ",
    price: 50000,
    duration: 60,
    imageUrl: "https://via.placeholder.com/150",
    category: "skin",
  },
  {
    id: "6",
    name: "Бүтэн биеийн массаж",
    description: "Стресс тайлах, булчинг суллах бүтэн биеийн массаж",
    price: 70000,
    duration: 60,
    imageUrl: "https://via.placeholder.com/150",
    category: "body",
  },
];
