export const stylists = [
  {
    id: "1",
    name: "Болормаа Бат",
    specialty: "Үсчин",
    experience: "8 жил",
    rating: 4.9,
    reviews: 142,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Болормаа орчин үеийн үс засалт, техник дээр мэргэшсэн.",
    availability: ["Даваа", "Мягмар", "Пүрэв", "Баасан"],
  },
  {
    id: "2",
    name: "Тэмүүжин Чинзориг",
    specialty: "Үсний өнгө оруулагч",
    experience: "10 жил",
    rating: 4.8,
    reviews: 118,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Тэмүүжин хамгийн шилдэг өнгө оруулах техникээр мэргэшсэн.",
    availability: ["Мягмар", "Лхагва", "Баасан", "Бямба"],
  },
  {
    id: "3",
    name: "Сараа Ганбат",
    specialty: "Маникюрчин",
    experience: "6 жил",
    rating: 4.7,
    reviews: 95,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Сараа төгс гоёлын хумсны урлагийг бүтээдэг.",
    availability: ["Даваа", "Лхагва", "Пүрэв", "Бямба"],
  },
  {
    id: "4",
    name: "Эрдэнэбилэг Баярсайхан",
    specialty: "Массажчин",
    experience: "12 жил",
    rating: 4.9,
    reviews: 201,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Эрдэнэбилэг эмчилгээний болон амралтын массаж мэргэшсэн.",
    availability: ["Даваа", "Мягмар", "Пүрэв", "Баасан", "Бямба"],
  },
];
