export const stylists = [
  {
    id: "1",
    name: "Emma Johnson",
    specialty: "Hair Stylist",
    experience: "8 years",
    rating: 4.9,
    reviews: 142,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Emma is specialized in modern haircuts and styling techniques.",
    availability: ["Monday", "Tuesday", "Thursday", "Friday"],
  },
  {
    id: "2",
    name: "David Chen",
    specialty: "Color Specialist",
    experience: "10 years",
    rating: 4.8,
    reviews: 118,
    imageUrl: "https://via.placeholder.com/150",
    bio: "David is our top colorist with expertise in highlights and balayage.",
    availability: ["Tuesday", "Wednesday", "Friday", "Saturday"],
  },
  {
    id: "3",
    name: "Sofia Rodriguez",
    specialty: "Nail Technician",
    experience: "6 years",
    rating: 4.7,
    reviews: 95,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Sofia creates beautiful nail art and perfect manicures.",
    availability: ["Monday", "Wednesday", "Thursday", "Saturday"],
  },
  {
    id: "4",
    name: "Michael Taylor",
    specialty: "Massage Therapist",
    experience: "12 years",
    rating: 4.9,
    reviews: 201,
    imageUrl: "https://via.placeholder.com/150",
    bio: "Michael specializes in therapeutic and relaxation massages.",
    availability: ["Monday", "Tuesday", "Thursday", "Friday", "Saturday"],
  },
];
